from sqlalchemy import Column, Integer, Boolean, String, DateTime, ForeignKey, func

from ..core.database import Base


class Subscription(Base):
    __tablename__ = "subscriptions"

    # Primary Key
    id = Column(
        Integer,
        primary_key=True,
        autoincrement=True,
        index=True
    )

    # Foreign Key -> users.id
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # true / false
    subscribe = Column(
        Boolean,
        nullable=False,
        default=True
    )

    # basic / pro
    plan = Column(
        String(20),
        nullable=False
    )

    # monthly / yearly
    validity = Column(
        String(20),
        nullable=False
    )

    # Automatically generated by PostgreSQL
    subscribed_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True
    )