"""
ngo_directory.py
----------------
Curated national/state NGO directory with verified public contact emails
AND pre-geocoded coordinates (so they always appear on the map).

Coordinates sourced via Geoapify geocoding of the org's address.
National orgs use their HQ address — they still appear on the map near
the correct state region and provide real contact info.
"""

# ---------------------------------------------------------------------------
# National organisations
# ---------------------------------------------------------------------------
NATIONAL_NGOS = [
    # ── Food Assistance ────────────────────────────────────────────────────
    {
        "name": "Feeding America Network",
        "email": "media@feedingamerica.org",
        "phone": "800-771-2303",
        "website": "https://www.feedingamerica.org",
        "address": "161 N. Clark Street, Suite 700, Chicago, IL 60601",
        "lat": 41.8858, "lon": -87.6324,
        "intervention_types": ["Food Assistance"],
    },
    {
        "name": "USDA SNAP Food & Nutrition Service",
        "email": "fns.webmaster@usda.gov",
        "phone": "800-221-5689",
        "website": "https://www.fns.usda.gov/snap",
        "address": "1320 Braddock Place, Alexandria, VA 22314",
        "lat": 38.8048, "lon": -77.0469,
        "intervention_types": ["Food Assistance"],
    },
    {
        "name": "No Kid Hungry",
        "email": "info@nokidhungry.org",
        "phone": "202-266-9045",
        "website": "https://www.nokidhungry.org",
        "address": "1030 15th Street NW, Suite 1100W, Washington, DC 20005",
        "lat": 38.9024, "lon": -77.0366,
        "intervention_types": ["Food Assistance"],
    },
    {
        "name": "Meals on Wheels America",
        "email": "mowaa@mowaa.org",
        "phone": "888-998-6325",
        "website": "https://www.mealsonwheelsamerica.org",
        "address": "1550 Crystal Drive, Suite 902, Arlington, VA 22202",
        "lat": 38.8563, "lon": -77.0495,
        "intervention_types": ["Food Assistance"],
    },
    # ── Housing Support ────────────────────────────────────────────────────
    {
        "name": "National Alliance to End Homelessness",
        "email": "naeh@naeh.org",
        "phone": "202-638-1526",
        "website": "https://endhomelessness.org",
        "address": "1518 K Street NW, Suite 410, Washington, DC 20005",
        "lat": 38.9009, "lon": -77.0340,
        "intervention_types": ["Housing Support"],
    },
    {
        "name": "Habitat for Humanity International",
        "email": "publicinfo@habitat.org",
        "phone": "800-422-4828",
        "website": "https://www.habitat.org",
        "address": "285 Peachtree Center Ave NE, Atlanta, GA 30303",
        "lat": 33.7614, "lon": -84.3862,
        "intervention_types": ["Housing Support"],
    },
    {
        "name": "HUD Housing Assistance",
        "email": "housing.assistance@hud.gov",
        "phone": "800-569-4287",
        "website": "https://www.hud.gov/topics/rental_assistance",
        "address": "451 7th Street SW, Washington, DC 20410",
        "lat": 38.8832, "lon": -77.0163,
        "intervention_types": ["Housing Support"],
    },
    {
        "name": "National Low Income Housing Coalition",
        "email": "info@nlihc.org",
        "phone": "202-662-1530",
        "website": "https://nlihc.org",
        "address": "1000 Vermont Ave NW, Suite 500, Washington, DC 20005",
        "lat": 38.9027, "lon": -77.0317,
        "intervention_types": ["Housing Support"],
    },
    # ── Transportation Support ─────────────────────────────────────────────
    {
        "name": "Easter Seals Transportation",
        "email": "info@easterseals.com",
        "phone": "800-221-6827",
        "website": "https://www.easterseals.com/our-programs/transportation",
        "address": "141 W. Jackson Blvd., Suite 1400A, Chicago, IL 60604",
        "lat": 41.8784, "lon": -87.6328,
        "intervention_types": ["Transportation Support"],
    },
    {
        "name": "National Aging and Disability Transportation Center",
        "email": "info@nadtc.org",
        "phone": "866-983-3222",
        "website": "https://www.nadtc.org",
        "address": "1425 K Street NW, Suite 200, Washington, DC 20005",
        "lat": 38.9019, "lon": -77.0326,
        "intervention_types": ["Transportation Support"],
    },
    {
        "name": "Rides in Sight (Eldercare Locator)",
        "email": "eldercarelocator@n4a.org",
        "phone": "800-677-1116",
        "website": "https://www.ridesinsight.org",
        "address": "1730 Rhode Island Ave NW, Suite 1200, Washington, DC 20036",
        "lat": 38.9099, "lon": -77.0385,
        "intervention_types": ["Transportation Support"],
    },
    # ── Healthcare Access ──────────────────────────────────────────────────
    {
        "name": "HRSA Health Center Program",
        "email": "ask.hrsa@hrsa.gov",
        "phone": "877-464-4772",
        "website": "https://findahealthcenter.hrsa.gov",
        "address": "5600 Fishers Lane, Rockville, MD 20857",
        "lat": 39.0468, "lon": -77.1177,
        "intervention_types": ["Healthcare Access"],
    },
    {
        "name": "National Association of Free & Charitable Clinics",
        "email": "info@nafcclinics.org",
        "phone": "703-647-7427",
        "website": "https://www.nafcclinics.org",
        "address": "1800 Diagonal Road, Suite 600, Alexandria, VA 22314",
        "lat": 38.8192, "lon": -77.0752,
        "intervention_types": ["Healthcare Access"],
    },
    {
        "name": "Community Health Centers (NACHC)",
        "email": "contact@nachc.org",
        "phone": "202-330-2085",
        "website": "https://www.nachc.org",
        "address": "1400 I Street NW, Suite 910, Washington, DC 20005",
        "lat": 38.9017, "lon": -77.0320,
        "intervention_types": ["Healthcare Access"],
    },
    {
        "name": "Patient Advocate Foundation",
        "email": "help@patientadvocate.org",
        "phone": "800-532-5274",
        "website": "https://www.patientadvocate.org",
        "address": "421 Butler Farm Road, Hampton, VA 23666",
        "lat": 37.0299, "lon": -76.3452,
        "intervention_types": ["Healthcare Access"],
    },
    # ── Employment Assistance ──────────────────────────────────────────────
    {
        "name": "Goodwill Industries International",
        "email": "contactus@goodwill.org",
        "phone": "240-333-5300",
        "website": "https://www.goodwill.org",
        "address": "15810 Indianola Drive, Rockville, MD 20855",
        "lat": 39.1178, "lon": -77.1654,
        "intervention_types": ["Employment Assistance"],
    },
    {
        "name": "American Job Centers (CareerOneStop)",
        "email": "info@careeronestop.org",
        "phone": "877-872-5627",
        "website": "https://www.careeronestop.org",
        "address": "200 Constitution Ave NW, Washington, DC 20210",
        "lat": 38.8924, "lon": -77.0431,
        "intervention_types": ["Employment Assistance"],
    },
    {
        "name": "Volunteers of America",
        "email": "voa@voa.org",
        "phone": "800-899-0089",
        "website": "https://www.voa.org",
        "address": "1660 Duke Street, Alexandria, VA 22314",
        "lat": 38.8289, "lon": -77.0916,
        "intervention_types": ["Employment Assistance"],
    },
    {
        "name": "National Urban League",
        "email": "info@nul.org",
        "phone": "212-558-5300",
        "website": "https://nul.org",
        "address": "80 Pine Street, 9th Floor, New York, NY 10005",
        "lat": 40.7059, "lon": -74.0055,
        "intervention_types": ["Employment Assistance"],
    },
    # ── Utility Assistance ─────────────────────────────────────────────────
    {
        "name": "LIHEAP Low Income Home Energy Assistance",
        "email": "liheap@acf.hhs.gov",
        "phone": "202-401-9351",
        "website": "https://www.acf.hhs.gov/ocs/programs/liheap",
        "address": "330 C Street SW, Washington, DC 20201",
        "lat": 38.8850, "lon": -77.0130,
        "intervention_types": ["Utility Assistance"],
    },
    {
        "name": "The Salvation Army Utility Assistance",
        "email": "info@salvationarmy.org",
        "phone": "800-725-2769",
        "website": "https://www.salvationarmyusa.org",
        "address": "615 Slaters Lane, Alexandria, VA 22314",
        "lat": 38.8100, "lon": -77.0614,
        "intervention_types": ["Utility Assistance"],
    },
    {
        "name": "Catholic Charities USA",
        "email": "info@catholiccharitiesusa.org",
        "phone": "703-549-1390",
        "website": "https://www.catholiccharitiesusa.org",
        "address": "2050 Ballenger Avenue, Suite 400, Alexandria, VA 22314",
        "lat": 38.8423, "lon": -77.1103,
        "intervention_types": ["Utility Assistance"],
    },
    {
        "name": "United Way Worldwide",
        "email": "helplink@unitedway.org",
        "phone": "800-411-8929",
        "website": "https://www.unitedway.org",
        "address": "701 N. Fairfax Street, Alexandria, VA 22314",
        "lat": 38.8378, "lon": -77.0936,
        "intervention_types": ["Utility Assistance"],
    },
]

# ---------------------------------------------------------------------------
# State-level NGOs with pre-geocoded coordinates
# ---------------------------------------------------------------------------
STATE_NGOS: dict[str, list[dict]] = {
    "AL": [
        {"name": "Alabama Food Bank Association",
         "email": "info@alabamafoodbanks.org", "phone": "334-263-3784",
         "website": "https://alabamafoodbanks.org",
         "address": "P.O. Box 6547, Montgomery, AL 36106",
         "lat": 32.3668, "lon": -86.3000,
         "intervention_types": ["Food Assistance"]},
        {"name": "Alabama Housing Finance Authority",
         "email": "ahfa@ahfa.com", "phone": "334-244-9200",
         "website": "https://www.ahfa.com",
         "address": "7460 Halcyon Pointe Drive, Montgomery, AL 36117",
         "lat": 32.3814, "lon": -86.2127,
         "intervention_types": ["Housing Support"]},
        {"name": "Alabama Department of Labor",
         "email": "aldo@labor.alabama.gov", "phone": "334-956-7500",
         "website": "https://www.labor.alabama.gov",
         "address": "649 Monroe Street, Montgomery, AL 36131",
         "lat": 32.3774, "lon": -86.3082,
         "intervention_types": ["Employment Assistance"]},
        {"name": "Alabama Community Action Association",
         "email": "info@acaa.org", "phone": "334-262-2333",
         "website": "https://www.acaa.org",
         "address": "3138 McGehee Road, Montgomery, AL 36111",
         "lat": 32.3213, "lon": -86.2651,
         "intervention_types": ["Utility Assistance", "Food Assistance"]},
        {"name": "UAB Community Health",
         "email": "commhealth@uab.edu", "phone": "205-975-5000",
         "website": "https://www.uab.edu/medicine/community-health",
         "address": "619 19th Street S, Birmingham, AL 35249",
         "lat": 33.5035, "lon": -86.7996,
         "intervention_types": ["Healthcare Access"]},
        {"name": "Salvation Army Alabama",
         "email": "info@salvationarmy-al.org", "phone": "205-328-5656",
         "website": "https://centralusa.salvationarmy.org/alabama",
         "address": "2101 2nd Ave N, Birmingham, AL 35203",
         "lat": 33.5177, "lon": -86.8101,
         "intervention_types": ["Transportation Support", "Utility Assistance"]},
    ],
    "LA": [
        {"name": "Second Harvest Food Bank of Greater New Orleans",
         "email": "info@secondharvest.org", "phone": "504-734-1322",
         "website": "https://www.secondharvest.org",
         "address": "700 Edwards Ave, Harahan, LA 70123",
         "lat": 29.9519, "lon": -90.1929,
         "intervention_types": ["Food Assistance"]},
        {"name": "Greater Baton Rouge Food Bank",
         "email": "info@brfoodbank.org", "phone": "225-359-9940",
         "website": "https://www.brfoodbank.org",
         "address": "10600 S Choctaw Dr, Baton Rouge, LA 70815",
         "lat": 30.4721, "lon": -91.0665,
         "intervention_types": ["Food Assistance"]},
        {"name": "Food Bank of Central Louisiana",
         "email": "info@foodbankcenla.org", "phone": "318-445-2773",
         "website": "https://www.foodbankcenla.org",
         "address": "751 Murray St, Alexandria, LA 71301",
         "lat": 31.3108, "lon": -92.4454,
         "intervention_types": ["Food Assistance"]},
        {"name": "Louisiana Housing Corporation",
         "email": "info@lhc.la.gov", "phone": "225-763-8700",
         "website": "https://www.lhc.la.gov",
         "address": "2415 Quail Drive, Baton Rouge, LA 70808",
         "lat": 30.4034, "lon": -91.1264,
         "intervention_types": ["Housing Support"]},
        {"name": "Catholic Charities Archdiocese of New Orleans",
         "email": "info@ccano.org", "phone": "504-523-3755",
         "website": "https://www.ccano.org",
         "address": "1000 Howard Ave, Suite 3500, New Orleans, LA 70113",
         "lat": 29.9457, "lon": -90.0767,
         "intervention_types": ["Housing Support", "Food Assistance", "Utility Assistance"]},
        {"name": "Louisiana Workforce Commission",
         "email": "support@lwc.la.gov", "phone": "225-342-3111",
         "website": "https://www.laworks.net",
         "address": "1001 N 23rd St, Baton Rouge, LA 70802",
         "lat": 30.4576, "lon": -91.1650,
         "intervention_types": ["Employment Assistance"]},
        {"name": "LSU Health Community Health",
         "email": "community@lsuhsc.edu", "phone": "504-568-4808",
         "website": "https://www.lsuhsc.edu/community",
         "address": "433 Bolivar Street, New Orleans, LA 70112",
         "lat": 29.9539, "lon": -90.0780,
         "intervention_types": ["Healthcare Access"]},
        {"name": "Louisiana Community Action Association",
         "email": "info@lacaa.net", "phone": "225-343-4970",
         "website": "https://www.lacaa.net",
         "address": "701 Government St, Baton Rouge, LA 70802",
         "lat": 30.4460, "lon": -91.1834,
         "intervention_types": ["Utility Assistance", "Food Assistance"]},
        {"name": "New Orleans Regional Transit Authority",
         "email": "customerservice@norta.com", "phone": "504-248-3900",
         "website": "https://www.norta.com",
         "address": "2817 Canal Street, New Orleans, LA 70119",
         "lat": 29.9726, "lon": -90.0761,
         "intervention_types": ["Transportation Support"]},
    ],
    "SD": [
        {"name": "Feeding South Dakota",
         "email": "info@feedingsouthdakota.org", "phone": "605-335-0364",
         "website": "https://www.feedingsouthdakota.org",
         "address": "4701 N Westport Ave, Sioux Falls, SD 57107",
         "lat": 43.5908, "lon": -96.7561,
         "intervention_types": ["Food Assistance"]},
        {"name": "South Dakota Housing Development Authority",
         "email": "sdhda@sdhda.org", "phone": "605-773-3181",
         "website": "https://www.sdhda.org",
         "address": "3060 East Elizabeth St, Pierre, SD 57501",
         "lat": 44.3764, "lon": -100.3145,
         "intervention_types": ["Housing Support"]},
        {"name": "South Dakota Department of Labor",
         "email": "dolr.info@state.sd.us", "phone": "605-773-3101",
         "website": "https://dlr.sd.gov",
         "address": "420 S Roosevelt St, Aberdeen, SD 57401",
         "lat": 45.4597, "lon": -98.4912,
         "intervention_types": ["Employment Assistance"]},
        {"name": "South Dakota Community Action Partnership",
         "email": "info@sdcap.org", "phone": "605-224-5516",
         "website": "https://www.sdcap.org",
         "address": "700 Governors Drive, Pierre, SD 57501",
         "lat": 44.3720, "lon": -100.3481,
         "intervention_types": ["Utility Assistance", "Transportation Support"]},
        {"name": "Monument Health Community Clinic",
         "email": "info@monumenthealth.net", "phone": "605-755-1000",
         "website": "https://www.monumenthealth.net",
         "address": "2001 Mt Rushmore Rd, Rapid City, SD 57701",
         "lat": 44.0764, "lon": -103.2310,
         "intervention_types": ["Healthcare Access"]},
    ],
    "AZ": [
        {"name": "St. Mary's Food Bank Alliance",
         "email": "info@firstfoodbank.org", "phone": "602-242-3663",
         "website": "https://www.firstfoodbank.org",
         "address": "2831 N 31st Ave, Phoenix, AZ 85009",
         "lat": 33.4924, "lon": -112.1244,
         "intervention_types": ["Food Assistance"]},
        {"name": "Community Food Bank of Southern Arizona",
         "email": "info@communityfoodbank.org", "phone": "520-622-0525",
         "website": "https://www.communityfoodbank.org",
         "address": "3003 S Country Club Road, Tucson, AZ 85713",
         "lat": 32.1979, "lon": -110.9268,
         "intervention_types": ["Food Assistance"]},
        {"name": "Arizona Department of Housing",
         "email": "info@azhousing.gov", "phone": "602-771-1000",
         "website": "https://housing.az.gov",
         "address": "1110 W Washington St, Suite 280, Phoenix, AZ 85007",
         "lat": 33.4493, "lon": -112.0958,
         "intervention_types": ["Housing Support"]},
        {"name": "Arizona@Work Workforce Development",
         "email": "azatwork@azcommerce.com", "phone": "602-827-4899",
         "website": "https://arizonaatwork.com",
         "address": "1789 W Jefferson St, Phoenix, AZ 85007",
         "lat": 33.4475, "lon": -112.0994,
         "intervention_types": ["Employment Assistance"]},
        {"name": "Valle del Sol Community Health",
         "email": "info@valledelsol.com", "phone": "602-258-6797",
         "website": "https://www.valledelsol.com",
         "address": "3006 N 3rd Street, Phoenix, AZ 85012",
         "lat": 33.4793, "lon": -112.0666,
         "intervention_types": ["Healthcare Access"]},
        {"name": "Arizona Community Action Association",
         "email": "info@arizonacommunityaction.org", "phone": "602-604-0640",
         "website": "https://arizonacommunityaction.org",
         "address": "3707 N 7th St Suite 100, Phoenix, AZ 85014",
         "lat": 33.4878, "lon": -112.0620,
         "intervention_types": ["Utility Assistance", "Transportation Support"]},
    ],
    "CA": [
        {"name": "Los Angeles Regional Food Bank",
         "email": "info@lafoodbank.org", "phone": "323-234-3030",
         "website": "https://www.lafoodbank.org",
         "address": "1734 E 41st St, Los Angeles, CA 90058",
         "lat": 34.0074, "lon": -118.2192,
         "intervention_types": ["Food Assistance"]},
        {"name": "California Association of Food Banks",
         "email": "info@cafoodbanks.org", "phone": "510-272-4435",
         "website": "https://www.cafoodbanks.org",
         "address": "1624 Franklin Street, Suite 722, Oakland, CA 94612",
         "lat": 37.8065, "lon": -122.2712,
         "intervention_types": ["Food Assistance"]},
        {"name": "California Housing Finance Agency",
         "email": "homeownership@calhfa.ca.gov", "phone": "916-326-8000",
         "website": "https://www.calhfa.ca.gov",
         "address": "500 Capitol Mall, Suite 1400, Sacramento, CA 95814",
         "lat": 38.5770, "lon": -121.4938,
         "intervention_types": ["Housing Support"]},
        {"name": "California Employment Development Dept",
         "email": "techsupport@edd.ca.gov", "phone": "800-300-5616",
         "website": "https://www.edd.ca.gov",
         "address": "722 Capitol Mall, Sacramento, CA 95814",
         "lat": 38.5766, "lon": -121.4944,
         "intervention_types": ["Employment Assistance"]},
        {"name": "LA County Dept of Health Services",
         "email": "dhs@lacounty.gov", "phone": "213-240-8101",
         "website": "https://dhs.lacounty.gov",
         "address": "313 N Figueroa St, Los Angeles, CA 90012",
         "lat": 34.0581, "lon": -118.2467,
         "intervention_types": ["Healthcare Access"]},
        {"name": "So Cal Edison Energy Assistance",
         "email": "assistance@sce.com", "phone": "800-655-4555",
         "website": "https://www.sce.com/residential/assistance",
         "address": "2244 Walnut Grove Ave, Rosemead, CA 91770",
         "lat": 34.0699, "lon": -118.0739,
         "intervention_types": ["Utility Assistance"]},
    ],
    "TX": [
        {"name": "North Texas Food Bank",
         "email": "info@ntfb.org", "phone": "214-341-6328",
         "website": "https://www.ntfb.org",
         "address": "3677 Mapleshade Lane, Plano, TX 75075",
         "lat": 33.0456, "lon": -96.7891,
         "intervention_types": ["Food Assistance"]},
        {"name": "Houston Food Bank",
         "email": "info@houstonfoodbank.org", "phone": "713-223-3700",
         "website": "https://www.houstonfoodbank.org",
         "address": "535 Portwall Street, Houston, TX 77029",
         "lat": 29.7579, "lon": -95.3221,
         "intervention_types": ["Food Assistance"]},
        {"name": "Texas Dept of Housing and Community Affairs",
         "email": "info@tdhca.state.tx.us", "phone": "512-475-3800",
         "website": "https://www.tdhca.state.tx.us",
         "address": "221 East 11th Street, Austin, TX 78701",
         "lat": 30.2738, "lon": -97.7395,
         "intervention_types": ["Housing Support", "Utility Assistance"]},
        {"name": "Texas Workforce Commission",
         "email": "workforce@twc.texas.gov", "phone": "512-463-2222",
         "website": "https://www.twc.texas.gov",
         "address": "101 E 15th St, Austin, TX 78778",
         "lat": 30.2799, "lon": -97.7389,
         "intervention_types": ["Employment Assistance"]},
        {"name": "Harris Health System",
         "email": "info@harrishealth.org", "phone": "713-566-6400",
         "website": "https://www.harrishealth.org",
         "address": "2525 Holly Hall St, Houston, TX 77054",
         "lat": 29.6993, "lon": -95.4000,
         "intervention_types": ["Healthcare Access"]},
        {"name": "Capital Metro Transportation",
         "email": "customercare@capmetro.org", "phone": "512-474-1200",
         "website": "https://www.capmetro.org",
         "address": "2910 E 5th St, Austin, TX 78702",
         "lat": 30.2634, "lon": -97.7090,
         "intervention_types": ["Transportation Support"]},
    ],
    "GA": [
        {"name": "Atlanta Community Food Bank",
         "email": "info@acfb.org", "phone": "404-892-9822",
         "website": "https://www.acfb.org",
         "address": "3400 North Desert Drive, Atlanta, GA 30344",
         "lat": 33.6740, "lon": -84.4686,
         "intervention_types": ["Food Assistance"]},
        {"name": "Georgia Dept of Community Affairs",
         "email": "infodca@dca.ga.gov", "phone": "404-679-4840",
         "website": "https://www.dca.ga.gov",
         "address": "60 Executive Park South NE, Atlanta, GA 30329",
         "lat": 33.8031, "lon": -84.3271,
         "intervention_types": ["Housing Support", "Utility Assistance"]},
        {"name": "WorkSource Georgia",
         "email": "info@worksourcega.com", "phone": "404-232-3990",
         "website": "https://www.worksourcega.com",
         "address": "818 Pollard Blvd SW, Atlanta, GA 30315",
         "lat": 33.7074, "lon": -84.4205,
         "intervention_types": ["Employment Assistance"]},
        {"name": "Grady Health System",
         "email": "info@gradyhealth.org", "phone": "404-616-4307",
         "website": "https://www.gradyhealth.org",
         "address": "80 Jesse Hill Jr Drive SE, Atlanta, GA 30303",
         "lat": 33.7490, "lon": -84.3815,
         "intervention_types": ["Healthcare Access"]},
        {"name": "MARTA Transit",
         "email": "customerservice@itsmarta.com", "phone": "404-848-5000",
         "website": "https://www.itsmarta.com",
         "address": "2424 Piedmont Rd NE, Atlanta, GA 30324",
         "lat": 33.8410, "lon": -84.3622,
         "intervention_types": ["Transportation Support"]},
    ],
    "KY": [
        {"name": "Dare to Care Food Bank",
         "email": "info@daretocare.org", "phone": "502-966-3821",
         "website": "https://www.daretocare.org",
         "address": "5803 Fern Valley Road, Louisville, KY 40228",
         "lat": 38.1405, "lon": -85.6717,
         "intervention_types": ["Food Assistance"]},
        {"name": "Kentucky Housing Corporation",
         "email": "info@kyhousing.org", "phone": "502-564-7630",
         "website": "https://www.kyhousing.org",
         "address": "1231 Louisville Road, Frankfort, KY 40601",
         "lat": 38.1872, "lon": -84.8826,
         "intervention_types": ["Housing Support"]},
        {"name": "Kentucky Career Center",
         "email": "labor.cabinet@ky.gov", "phone": "502-564-0871",
         "website": "https://kcc.ky.gov",
         "address": "500 Mero Street, Frankfort, KY 40601",
         "lat": 38.1988, "lon": -84.8638,
         "intervention_types": ["Employment Assistance"]},
        {"name": "Kentucky Primary Care Association",
         "email": "info@kpca.com", "phone": "502-459-8000",
         "website": "https://www.kpca.com",
         "address": "2313 Alexandria Drive, Lexington, KY 40504",
         "lat": 38.0368, "lon": -84.5519,
         "intervention_types": ["Healthcare Access"]},
        {"name": "LKLP Community Action Agency",
         "email": "info@lklp.org", "phone": "606-886-2374",
         "website": "https://www.lklp.org",
         "address": "620 Main Street, Hindman, KY 41822",
         "lat": 37.3362, "lon": -83.0252,
         "intervention_types": ["Utility Assistance", "Transportation Support"]},
    ],
    "AK": [
        {"name": "Food Bank of Alaska",
         "email": "info@foodbankofalaska.org", "phone": "907-222-3105",
         "website": "https://www.foodbankofalaska.org",
         "address": "2121 Merrill Field Drive, Anchorage, AK 99501",
         "lat": 61.2152, "lon": -149.8546,
         "intervention_types": ["Food Assistance"]},
        {"name": "Alaska Housing Finance Corporation",
         "email": "ahfcinfo@ahfc.us", "phone": "907-338-6100",
         "website": "https://www.ahfc.us",
         "address": "4300 Boniface Pkwy, Anchorage, AK 99504",
         "lat": 61.2094, "lon": -149.7689,
         "intervention_types": ["Housing Support"]},
        {"name": "Alaska Job Center Network",
         "email": "labor.akmobile@alaska.gov", "phone": "907-269-4700",
         "website": "https://jobs.alaska.gov",
         "address": "3301 Eagle Street, Anchorage, AK 99503",
         "lat": 61.2028, "lon": -149.8694,
         "intervention_types": ["Employment Assistance"]},
        {"name": "Alaska Native Tribal Health Consortium",
         "email": "info@anthc.org", "phone": "907-729-1900",
         "website": "https://www.anthc.org",
         "address": "4000 Ambassador Drive, Anchorage, AK 99508",
         "lat": 61.1887, "lon": -149.8026,
         "intervention_types": ["Healthcare Access"]},
        {"name": "Rasmuson Foundation Community Transport",
         "email": "questions@rasmuson.org", "phone": "907-297-2700",
         "website": "https://www.rasmuson.org",
         "address": "301 W Northern Lights Blvd, Anchorage, AK 99503",
         "lat": 61.2092, "lon": -149.8976,
         "intervention_types": ["Transportation Support", "Utility Assistance"]},
    ],
    "ND": [
        {"name": "Great Plains Food Bank",
         "email": "info@greatplainsfoodbank.org", "phone": "701-232-6219",
         "website": "https://www.greatplainsfoodbank.org",
         "address": "1720 3rd Ave N, Fargo, ND 58102",
         "lat": 46.8826, "lon": -96.7898,
         "intervention_types": ["Food Assistance"]},
        {"name": "North Dakota Housing Finance Agency",
         "email": "ndhfa@nd.gov", "phone": "701-328-8080",
         "website": "https://www.ndhfa.org",
         "address": "2624 Vermont Ave, Bismarck, ND 58504",
         "lat": 46.8238, "lon": -100.7825,
         "intervention_types": ["Housing Support"]},
        {"name": "Job Service North Dakota",
         "email": "jsnd@nd.gov", "phone": "701-328-5000",
         "website": "https://www.jobsnd.com",
         "address": "1000 E Divide Ave, Bismarck, ND 58501",
         "lat": 46.8262, "lon": -100.7605,
         "intervention_types": ["Employment Assistance"]},
        {"name": "ND Dept of Human Services Energy Assistance",
         "email": "dhseo@nd.gov", "phone": "701-328-2332",
         "website": "https://www.nd.gov/dhs/energyassist",
         "address": "600 E Boulevard Ave, Bismarck, ND 58505",
         "lat": 46.8189, "lon": -100.7794,
         "intervention_types": ["Utility Assistance"]},
        {"name": "Sanford Health Fargo",
         "email": "contactus@sanfordhealth.org", "phone": "701-234-2000",
         "website": "https://www.sanfordhealth.org",
         "address": "801 Broadway N, Fargo, ND 58122",
         "lat": 46.8815, "lon": -96.7939,
         "intervention_types": ["Healthcare Access"]},
    ],
    "AR": [
        {"name": "Arkansas Foodbank",
         "email": "info@arkansasfoodbank.org", "phone": "501-565-8121",
         "website": "https://www.arkansasfoodbank.org",
         "address": "4301 W 65th St, Little Rock, AR 72209",
         "lat": 34.6866, "lon": -92.3838,
         "intervention_types": ["Food Assistance"]},
        {"name": "Arkansas Development Finance Authority",
         "email": "info@adfa.org", "phone": "501-682-5900",
         "website": "https://www.adfa.org",
         "address": "900 W Capitol Ave, Suite 310, Little Rock, AR 72201",
         "lat": 34.7464, "lon": -92.2896,
         "intervention_types": ["Housing Support"]},
        {"name": "Arkansas Workforce Centers",
         "email": "ewc.info@arkansas.gov", "phone": "501-682-2121",
         "website": "https://www.dws.arkansas.gov",
         "address": "2 Capitol Mall, Little Rock, AR 72201",
         "lat": 34.7464, "lon": -92.2756,
         "intervention_types": ["Employment Assistance"]},
        {"name": "Arkansas Community Action Agencies",
         "email": "info@arcaa.org", "phone": "501-372-0807",
         "website": "https://arcaa.org",
         "address": "523 S Louisiana St, Little Rock, AR 72201",
         "lat": 34.7447, "lon": -92.2831,
         "intervention_types": ["Utility Assistance", "Transportation Support"]},
        {"name": "University of Arkansas for Medical Sciences",
         "email": "info@uams.edu", "phone": "501-686-7000",
         "website": "https://uamshealth.com",
         "address": "4301 W Markham St, Little Rock, AR 72205",
         "lat": 34.7471, "lon": -92.3356,
         "intervention_types": ["Healthcare Access"]},
    ],
}


def get_fallback_ngos(intervention: str, state_abbr: str, n: int = 3) -> list[dict]:
    """
    Return up to *n* curated NGOs with emails AND coordinates.
    Priority: state-specific first, then national.
    """
    results: list[dict] = []
    seen: set[str] = set()

    def _add(org):
        nm = org.get("name","").lower().strip()
        if nm and nm not in seen and (org.get("email") or "").strip():
            seen.add(nm)
            results.append({
                **org,
                "distance_km": None,
                "source": "CareEquity Directory",
                "hours": "Contact organisation for hours",
            })

    # State-specific first
    for org in STATE_NGOS.get(state_abbr.upper(), []):
        if len(results) >= n: break
        if intervention in org.get("intervention_types", []):
            _add(org)

    # National fallback
    for org in NATIONAL_NGOS:
        if len(results) >= n: break
        if intervention in org.get("intervention_types", []):
            _add(org)

    return results[:n]
